accounts/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('index/', index),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('', include('django.contrib.auth.urls')),
    path('profile/', profile, name='profile'),
]

blog/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import (
    create_post,
    BlogDetailView,
    BlogDeleteView,
    BlogListView,
    # BlogUpdateView
    update_blog,
    UserBlogListView,
)
urlpatterns = [
    path('', RedirectView.as_view(url="/")),
    path('list/', UserBlogListView.as_view(), name='user_blog_list'), #те на кого подписан
    path('search/', BlogListView.as_view(), name='list'),
    path('create/', create_post, name='create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('<int:id>/edit/', update_blog, name='edit'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='delete'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static


from blog.views import BlogListView
from .views import SearchView, about_page, faq, agreement
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('total/', BlogListView.as_view(), name='total'),#общий блог
    path('about/', about_page, name="about"),
    path('faq/', faq, name="faq"),
    path('agreement/', agreement, name="agreement"),
    path('', views.home, name="home"),
    # path('user/search/', SearchView.as_view(), name='search'),#all mentor list
    path('', include(('accounts.urls', 'profiles'), namespace='profiles')),
    path('api/blog/', include(('blog.api.urls', 'blog-api'), namespace='blog-api')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('', include('django.contrib.auth.urls')),
    path('403', views.forbidden_view, name='403'),
    path('chat/', include('chat.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    name = models.CharField(max_length=100)
    tag = models.ManyToManyField('Tag')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Company(models.Model):
    name = models.CharField(max_length=100)
    owner = models.ManyToManyField(Profile, related_name="company")

    def __str__(self):
        return self.name

    def accept_request(self, id_user):
        request = Request.objects.get(profile=id_user)
        request.active = True
        request.save()
        request.checking()
        return request.active


class EmployesInCompany(models.Model):
    employee = models.ManyToManyField(Profile)
    company = models.OneToOneField(Company, on_delete=models.CASCADE, related_name="employes")

    def __str__(self):
        return self.company.name


class Request(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="requests")
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.profile.name + self.company.name

    def checking(self):
        if self.active:
            self.company.employes.employee.add(self.profile)
            return self.active



class Tag(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

blog/models.py
from django.conf import settings
from django.db import models
# from accounts.models import User
from django.urls import reverse
from PIL import Image
from accounts.models import User


class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"pk": self.pk})


class BlogImage(models.Model):
    image = models.ImageField(null=True, blank=True, upload_to='blog_images')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.blog.title}.jpg'

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 2000 or img.width > 2000:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Profile

User = get_user_model()


class TagForm(forms.Form):
    tag = forms.CharField()


class UserRegisterForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Password must match")
        return password2

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__icontains=username).exists():
            raise forms.ValidationError('This username is taken')
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email__icontains=email).exists():
            raise forms.ValidationError('This email is taken')
        return email


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['tag']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

accounts/views.py
from django.shortcuts import render
from .forms import TagForm
from .models import *
from django.views.generic.edit import FormView
from .forms import UserRegisterForm, ProfileUpdateForm, UserUpdateForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

User = get_user_model()


class UserRegisterView(FormView):
    template_name = 'accounts/user_register_form.html'
    form_class = UserRegisterForm
    success_url = '/'

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        new_user = User.objects.create(username=username, email=email)
        new_user.set_password(password)
        new_user.save()
        return super(UserRegisterView, self).form_valid(form)


def index(request):
    if request.method == 'POST':
        tag_form = TagForm(request.POST)
        if tag_form.is_valid():
            tags = tag_form.cleaned_data.get('tag')
            tags = tags.split('#')[1:]
            # print(tag)
            for tag in tags:
                obj, created = Tag.objects.filter(title=tag).get_or_create(title=tag)
            print(obj)
            return render(request, 'index.html', locals())

    else:
        tag_form = TagForm()
    return render(request, 'index.html', locals())


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profiles:profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/blog_user_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <main>
        <div class="background-blobs">
            <svg class="bg-svg" id="blobShape2" viewBox="0 0 500 500">
                <clipPath></clipPath>
                <path
                        fill="url(#g2)"
                        d="M 184,127.4 C 235.4,92.39 319.7,79.27 359.9,132.2 383.2,163 357.1,216.6 355.8,258.8 354.8,291.2 371.3,332.9 352.9,356 306.1,414.4 205.1,419.3 153.7,367.2 123.8,336.8 128.6,272.1 136.1,225.2 142.1,187.8 157,145.7 184,127.4 Z"
                />
                <linearGradient id="g2" x1="0%" y1="0%" x2="100%" y2="100%">
                    <stop offset="0" stop-color="#fefefe" />
                    <stop offset="1" stop-color="#452958" />
                </linearGradient>
            </svg>
            <section>
                <div
                        class="container col-lg-8 col-md-10 col-sm-12"
                        id="blog__blog-cards"
                >
                    <h2 class="font-title">Публикации ментора</h2>
                    {% for blog in object.blog_set.all %}

                        <div class="blog-card">
                            <div class="blog-card__blog-card-header">
                                <div class="blog-card__blog-card-header__avatar">
                                    <img src="{{ blog.user.profile.image.url }}">
                                </div>
                                <div class="blog_card__blog-card-header__username">
                                    <h4 class="font-subtitle"><a href="/{{ blog.user.username }}">{{ blog.user.first_name }} {{ blog.user.last_name }}</a></h4>
                                    <p class="font-text-sm">{{ blog.timestamp|timesince }}</p>
                                </div>
                            </div>
                            <div class="blog-card__blog-card-body">
                                <h4 class="font-title-sm">
                                    <a href="{% url 'blog:detail' blog.id %}"
                                    >{{ blog.title }}</a
                                    >
                                </h4>
                                <p class="font-text">
                                    {{ blog.content }}
                                </p>

                                <div class="blog-card__blog-card-body__img">
{#                                    <img src="{{ blog.blogimage_set.image.url }}" />#}
{#                                    {% if object.blogimage_set.first %}#}
                                        <img src="{{ blog.blogimage_set.first.image.url }}"/>
{#                                    {% else %}#}
{#                                      <p>No photo</p>#}
{#                                    {% endif %}#}
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <h5 class="font-text mt-5">Пока публикаций нет</h5>
                    {% endfor %}
                </div>
            </section>
        </div>
    </main>
{% endblock content %}





{#<div class="row mt-2">#}
{#        <div class="col-sm-3 col-xs-12">#}
{#            <h3>{{ object.username }}</h3>#}
{#            <hr>#}
{#            <div class="col-sm-9 col-xs-12">#}
{#                <h3>Blog</h3>#}
{#                {% for blog in object.blog_set.all %}#}
{#                    <article class="media content-section">#}
{#                        <div class="media-body">#}
{#                            <div class="article-metadata">#}
{#                                <small class="text-muted">{{ blog.timestamp|timesince }}</small>#}
{#                            </div>#}
{#                            <h2><a class="article-title" href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a>#}
{#                            </h2>#}
{#                            <p class="article-content">{{ blog.content }}</p>#}
{#                        </div>#}
{#                    </article>#}
{#                    <hr>#}
{#                {% empty %}#}
{#                    <h5>No blog yet.</h5>#}
{#                {% endfor %}#}
{#            </div>#}
{#        </div>#}

accounts/templates/accounts/following.html
{% extends 'base.html' %}
{% block title %} Мои подписки {% endblock title %}
{% block content %}
<main>
  <div class="background-blobs">
    <svg class="bg-svg" id="blobShape7" viewBox="0 0 500 500">
      <clipPath></clipPath>
      <path
        fill="url(#g7)"
        d="M 42.83,227.7 C 58.04,162.6 148.6,142.8 209,113.1 257.1,89.44 320.1,30.73 362.2,63.69 401.6,94.57 329.8,166.3 349.1,212.1 367.3,255.2 453,255.4 457.9,301.8 464.4,362.5 405,452.6 343.6,445.7 281.1,438.6 319.7,305.1 263.6,276.7 210.8,250 142.4,334.1 88.72,309.2 60.22,296 35.75,258 42.83,227.7 Z"
      />
      <linearGradient id="g7" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0" stop-color="#097976" />
        <stop offset="1" stop-color="#a23d8a" />
      </linearGradient>
    </svg>
    <section>
      <div class="container mentee-account">
        <div class="col-lg-9 col-md-12 col-sm-12 mentee-account__content">
          <h2 class="font-title">
            Мои Подписки
          </h2>
          <div class="mentee-account__content__subscriptions">
            {% for user in object.profile.get_following %}

            <div
              class="mentee-account__content__subscriptions__sub-card col-lg-4 col-md-6 col-sm-12"
            >
              <div
                class="mentee-account__content__subscriptions__sub-card__img"
              >
                <img src="{{ user.profile.image.url }}" />
              </div>
              <p
                class="font-text mentee-account__content__subscriptions__sub-card__name"
              >
                <a href="/{{ user.username }}"
                  >{{ user.first_name }} {{ user.last_name }} </a
                ><br />
              </p>
              <p
                class="font-text-sm mentee-account__content__subscriptions__sub-card__position"
              >
                {{ user.profile.position }}
              </p>
            </div>
            {% empty %}
            <h5 class="font-text">Вы пока ни на кого не подписаны</h5>
            {% endfor %}
          </div>
        </div>
        <div class="col-lg-3 col-md-12 col-sm-12 account-sidebar">
          <ul class="account-sidebar__nav">
            <li
              class="font-link account-sidebar__nav__nav-item "
              id="sidebar-feed"
            >
              <div id="sidebar-icon-feed"></div>
              <a href="/{{ user.username }}/blog">Мои публикации</a>
            </li>
            <li
              class="font-link account-sidebar__nav__nav-item"
              id="sidebar-settings"
            >
              <div id="sidebar-icon-settings"></div>
              <a href="{% url 'profiles:profile' %}">Настройки профиля</a>
            </li>
            <li
              class="font-link account-sidebar__nav__nav-item active"
              id="sidebar-follows"
            >
              <div id="sidebar-icon-follows"></div>
              <a href="/{{ user.username }}/following">Мои подписки</a>
            </li>
            <li
              class="font-link account-sidebar__nav__nav-item"
              id="sidebar-create"
            >
              <div id="sidebar-icon-create"></div>
              <a href="{% url 'blog:create' %}">Создать пост</a>
            </li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</main>
{% endblock %} 

accounts/templates/accounts/profile.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title %}Личный
кабинет{% endblock title %} {% block content %}
<main>
  <div class="background-blobs">
    <svg class="bg-svg" id="blobShape6" viewBox="0 0 500 500">
      <clipPath></clipPath>
      <path
        fill="url(#g6)"
        d="M 47.99,295.7 C 44.25,252.9 72.33,195.7 110.4,167 169.6,122.4 259,106.1 329.6,128.8 381.3,145.4 428,193 443.7,245 453.3,277 464.9,322.4 424.6,343.5 369,372.7 304.2,310.1 239.1,319 190.9,325.5 153,380 107.6,373.4 64.97,367.3 50.68,326.4 47.99,295.7 Z"
      />
      <linearGradient id="g6" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0" stop-color="#eeaeca" />
        <stop offset="1" stop-color="#94bbe9" />
      </linearGradient>
    </svg>
    <section>
      <div class="container mentor-account">
        <div class="col-lg-9 col-md-12 col-sm-12 mentor-account__form">
          <h2 class="font-title">
            Настройки Профиля
          </h2>
          <div class="mt-5">
            <h2 class="font-title-sm ">{{ user.first_name }} {{ user.last_name }}</h2>
            <p class="font-text">{{ user.email }}</p>
          </div>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ u_form.as_p }}
            {{ p_form.as_p }}

            <button class="btn btn-primary form-btn mt-5" type="submit">
              Сохранить
            </button>
          </form>
        </div>
        <div class="col-lg-3 col-md-12 col-sm-12 account-sidebar">
          <ul class="account-sidebar__nav">
            <li
              class="font-link account-sidebar__nav__nav-item "
              id="sidebar-feed"
            >
              <div id="sidebar-icon-feed"></div>
              <a href="/{{ user.username}}/blog">Мои публикации</a>
            </li>
            <li
              class="font-link account-sidebar__nav__nav-item active"
              id="sidebar-settings"
            >
              <div id="sidebar-icon-settings"></div>
              <a href="#">Настройки профиля</a>
            </li>
            <li
              class="font-link account-sidebar__nav__nav-item"
              id="sidebar-follows"
            >
              <div id="sidebar-icon-follows"></div>
              <a href="/{{ user.username}}/following">Мои подписки</a>
            </li>
            <li
            class="font-link account-sidebar__nav__nav-item"
            id="sidebar-create"
          >
            <div id="sidebar-icon-create"></div>
            <a href="{% url 'blog:create' %}">Создать пост</a>
          </li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</main>

{% endblock content %}

accounts/templates/accounts/user_list.html
{% extends "base.html" %}

{% block content %}
    <form method="GET" class="mt-5 mb-4" action="{% url 'profiles:user_list' %}">
        <input type="text" name="q" placeholder="Search" value="{{ request.GET.q }}">
        <input type="submit" value="Search">
      </form>
    <h1>Users</h1>

    <ul>
    {% for instance in object_list  %}
        <li><a href="/{{ user.username}}/">{{ instance.username }}</a>
    {% empty %}
        <li>No Tags yet.</li>
    {% endfor %}

    </ul>

{% endblock content %}

accounts/templates/accounts/user_list_view.html
{% extends "base.html" %}
{%  block title %}
    Публикации ментора
{%  endblock title %}
{% block content %}
    <main>
        <div class="background-blobs">
            <svg class="bg-svg" id="blobShape3" viewBox="0 0 500 500">
                <clipPath></clipPath>
                <path
                        fill="url(#g3)"
                        d="M 402.7,215.5 C 433.9,280.4 488.1,367.2 447.7,426.8 410.1,482.2 316.7,460.2 249.7,460.6 182.8,461.1 88.08,485.5 51.26,429.5 10.29,367.3 73.19,279.4 106.9,213 141.8,144 176.6,33.65 253.9,33.7 332.2,33.75 368.8,144.9 402.7,215.5 Z"
                />
                <linearGradient id="g3" x1="0%" y1="0%" x2="100%" y2="100%">
                    <stop offset="0" stop-color="#94d6ba" />
                    <stop offset="1" stop-color="#b5a9c4" />
                </linearGradient>
            </svg>
            <section>
                <div
                        class="container col-lg-8 col-md-10 col-sm-12"
                        id="blog__blog-cards"
                >
                    <h2 class="font-title">Публикации ментора</h2>
                    {% for blog in object_list %}
                        <div class="blog-card">
                            <div class="blog-card__blog-card-header">
                                <div class="blog-card__blog-card-header__avatar">
                                    <img src="{{ blog.user.profile.image.url }}" />
                                </div>
                                <div class="blog_card__blog-card-header__username">
                                    <h4 class="font-subtitle"><a href="{% url 'profiles:account_detail' object.user.username %}">{{ blog.user.first_name }} {{ blog.user.last_name }}</a></h4>
                                    <p class="font-text-sm">{{ blog.timestamp | timesince }}</p>
                                </div>
                            </div>
                            <div class="blog-card__blog-card-body">
                                <h4 class="font-title-sm">
                                    <a href="{% url 'blog:detail' blog.id %}">
                                        {{ blog.title }}
                                    </a>
                                </h4>

                                <p class="font-text">
                                    {{ blog.content }}
                                </p>
                                <div class="blog-card__blog-card-body__img">
                                    <img src="{{ blog.blogimage_set.first.image.url }}" />
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <h4 class="font-title-md">У данного ментора пока нет публикаций</h4>
                    {% endfor %}
                </div>
            </section>
        </div>
    </main>
{% endblock content %}

accounts/templates/accounts/user_register_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block title %}Регистрация{% endblock title %}


{% block content %}

    <main>
        <div class="mentor-registration-block container">
            <section>
                <h4 class="font-title">
                    Форма регистрации ментора
                </h4>

                <form class='form {% if form_class %}{{ form_class }}{% endif %}' method='POST' action="{% if action_url %}{{ action_url }}{% endif %}">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button
                            id="mentor-account__form__btn"
                            type="submit"
                            value="Создать аккаунт"
                            class="btn btn-primary form_btn"
                    >
                        Создать аккаунт
                    </button>
                </form>
            </section>
        </div>
    </main>
{% endblock content %}