accounts/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('index/', index),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('', include('django.contrib.auth.urls')),
    path('profile/', profile, name='profile'),
]

blog/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import (
    create_post,
    BlogDetailView,
    BlogDeleteView,
    BlogListView,
    # BlogUpdateView
    update_blog,
    UserBlogListView,
)
urlpatterns = [
    path('', RedirectView.as_view(url="/")),
    path('list/', UserBlogListView.as_view(), name='user_blog_list'), #те на кого подписан
    path('search/', BlogListView.as_view(), name='list'),
    path('create/', create_post, name='create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('<int:id>/edit/', update_blog, name='edit'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='delete'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static


from blog.views import BlogListView
from .views import SearchView, about_page, faq, agreement
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('total/', BlogListView.as_view(), name='total'),#общий блог
    path('about/', about_page, name="about"),
    path('faq/', faq, name="faq"),
    path('agreement/', agreement, name="agreement"),
    path('', views.home, name="home"),
    # path('user/search/', SearchView.as_view(), name='search'),#all mentor list
    path('', include(('accounts.urls', 'profiles'), namespace='profiles')),
    path('api/blog/', include(('blog.api.urls', 'blog-api'), namespace='blog-api')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('', include('django.contrib.auth.urls')),
    path('403', views.forbidden_view, name='403'),
    path('chat/', include('chat.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends "base.html" %}
{% block title %}О проекте{% endblock title %}
{% block content %}
    <main class="aboutpage ">
        <div class="background-blobs">
            <svg class="bg-svg" id="blobShape3" viewBox="0 0 500 500">
                <clipPath></clipPath>
                <path
                        fill="url(#g3)"
                        d="M 402.7,215.5 C 433.9,280.4 488.1,367.2 447.7,426.8 410.1,482.2 316.7,460.2 249.7,460.6 182.8,461.1 88.08,485.5 51.26,429.5 10.29,367.3 73.19,279.4 106.9,213 141.8,144 176.6,33.65 253.9,33.7 332.2,33.75 368.8,144.9 402.7,215.5 Z"
                />
                <linearGradient id="g3" x1="0%" y1="0%" x2="100%" y2="100%">
                    <stop offset="0" stop-color="#94d6ba" />
                    <stop offset="1" stop-color="#b5a9c4" />
                </linearGradient>
            </svg>
            <section class="container">
                <div class="aboutpage__first-block">
                    <h4 class="font-title">
                        О проекте
                    </h4>
                    <div class="aboutpage__first-block__content">
                        <div class="aboutpage__first-block__left-div col-md-4">
                            <div class="aboutpage__first-block__img"></div>
                        </div>

                        <div
                                class="aboutpage__first-block__right-div col-lg-8 col-md-12 col-sm-12"
                        >
                            <div class="aboutpage__first-block__title"></div>
                            <div class="aboutpage__first-block__text">
                                <h4 class="font-text-md ">
                                    Mentor.kg - это платформа, где наставники и ученики могут
                                    найти друг друга и соединиться. Чтобы получить что-то в
                                    жизни, бизнесе, учебе, отношениях или чем-то еще, важно
                                    получить руководство от наставника. Но найти правильного
                                    наставника сложно. Mentor.kg предоставляет простой способ
                                    связаться с наставниками и учениками в любой категории.
                                </h4>
                                <p class="font-text-md ">
                                    Объединяя поколения, меняем мир. Мы собираем на одной
                                    площадке опытных экспертов и тех, кто только начинает
                                    осваивать новые области знаний в науке и бизнесе. Наши
                                    менторы делятся своей экспертизой и опытом бесплатно. Многие
                                    из наших менти – люди, которые в будущем будут формировать
                                    ключевые тренды в науке и бизнесе, как в Кыргызстане, так и
                                    за рубежом.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <div class="aboutpage__quote-block">
                <section class="container">
                    <h4 class="font-text-md">
                        «Знание существует, чтобы его распространять»
                    </h4>
                    <p class="font-text-md">- Эмерсон Ральф Уолдо</p>
                </section>
            </div>
            <section class="container">
                <div class="aboutpage__mission-block">
                    <h4 class="font-title">
                        Наша миссия
                    </h4>
                    <div class="aboutpage__mission-block__cards-div">
                        <div class="col-lg-4 col-md-6 col-sm-12">
                            <div class="aboutpage__mission-block__card card">
                                <div class="aboutpage__mission-block__card__img-bg">
                                    <div class="aboutpage__mission-block__card__img-bg-text">
                                        <img
                                                src="/static/icons/aim.png"
                                                style="opacity: .8"
                                                width="50px"
                                                height="50px"
                                                alt=""
                                        />
                                        <h4 class="font-title-sm">В чем наша цель</h4>
                                    </div>
                                </div>
                                <div class="aboutpage__mission-block__card__text">
                                    <p class="font-text-md">
                                        Наша цель – обеспечить передачу знаний и опыта
                                        предпринимателям и специалистам и помочь им найти
                                        эффективные решения актуальных бизнес-задач, улучшить
                                        показатели компании
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6 col-sm-12">
                            <div class="aboutpage__mission-block__card card">
                                <div class="aboutpage__mission-block__card__img-bg">
                                    <div class="aboutpage__mission-block__card__img-bg-text">
                                        <img
                                                src="/static/icons/people.png"
                                                style="opacity: .8"
                                                width="50px"
                                                height="50px"
                                                alt=""
                                        />
                                        <h4 class="font-title-sm">Как мы к ней идем</h4>
                                    </div>
                                </div>
                                <div class="aboutpage__mission-block__card__text">
                                    <p class="font-text-md">
                                        Мы собрали на нашей онлайн-платформе лучших
                                        профессионалов, готовых делиться знаниями, быть
                                        наставниками и работать на повышение личной продуктивности
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-sm-12">
                            <div class="aboutpage__mission-block__card card">
                                <div class="aboutpage__mission-block__card__img-bg">
                                    <div class="aboutpage__mission-block__card__img-bg-text">
                                        <img
                                                src="/static/icons/hands.png"
                                                style="opacity: .8"
                                                width="50px"
                                                height="50px"
                                                alt=""
                                        />
                                        <h4 class="font-title-sm">Во что мы верим</h4>
                                    </div>
                                </div>
                                <div class="aboutpage__mission-block__card__text">
                                    <p class="font-text-md">
                                        Мы верим, что наставничество и советы опытных
                                        профессионалов помогут найти ответы на самые сложные
                                        вопросы, которые периодически возникают у любого человека.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="container"></section>
        </div>
    </main>
{% endblock content%}

templates/agreement.html
{% extends "base.html" %}
{% block title %}Пользовательское соглашение{% endblock title %}
{% block content %}
<main>
  <section>
    <div class="container">
      <div class="col-lg-9 col-md-12 col-sm-12">
        <h2 class="font-title">
          Пользовательское соглашение
        </h2>
        <div class="agreement">
          <p class="font-text">Пользовательское соглашение Mentor.kg</p>
          <p class="font-text">
            Настоящее Пользовательское соглашение (далее по тексту –
            «Соглашение») заключается между:
            <br />
            Обществом с ограниченной ответственностью «Эксперум» (далее по
            тексту – «Администрация»)
            <br />
            Посетителем сети Интернет (любым физическим лицом, индивидуальным
            предпринимателем, юридическим лицом, далее по тексту – «Посетитель»)
            <br />
            Программой для ЭВМ интернет сайт «Experum.ru» (далее по тексту –
            «Сайт»).
            <br />
            Сайт доступен в сети Интернет по адресу
            <a href="./index.html" class="font-link">https://mentor.kg</a> и
            представляет собой совокупность программ для ЭВМ, баз данных,
            обеспечивающих функционирование Сайта, а также совокупность услуг,
            предоставляемых Посетителям при использовании Сайта, в том числе в
            режиме онлайн. Перед началом использования Сайта и входящего в него
            программного обеспечения внимательно ознакомьтесь с условиями
            настоящего Соглашения. С момента как Посетитель начинает
            использовать Сайт/его отдельные функции, либо прошел процедуру
            регистрации, Соглашение вступает в силу, а Посетитель считается
            принявшим условия Соглашения, а также условия всех указанных ниже
            документов, в полном объеме, без всяких оговорок и исключений. Если
            вы не согласны с условиями настоящего Соглашения, вы не можете
            использовать Сайт.
          </p>
        </div>
      </div>
      <div class="col-4"></div>
    </div>
  </section>
</main>
{% endblock content%}

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/style.css' %}"
    />
    <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/bootstrap-grid.css' %}"
    />
    <link
            rel="stylesheet"
            type="text/css"
            href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.css"
    />
    <link
            rel="stylesheet"
            type="text/css"
            href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css"
    />
    <title> {%  block title %}{%  endblock title %}</title>
</head>
<body>
<header class="header">
    <div class="container">
        <div class="header-upper">
            <div class="header-upper-wrapper">
                <div class="header__header-upper__logo">
                    <h2 class="font-subtitle">
                        <a href="{% url 'home' %}">Mentor.kg</a>
                    </h2>
                </div>
                <ul class="header__header-upper__nav">
                    {% if user.is_authenticated %}
                        <li class="header__header-upper__nav__nav-item font-link">
                            <a href="{% url 'about' %}">О проекте</a>
                        </li>
                        <li class="header__header-upper__nav__nav-item font-link">
                            <a href="{% url 'total' %}">Блог</a>
                        </li>
                        <li class="header__header-upper__nav__nav-item font-link">
                            <a href="">Наши менторы</a>
                        </li>
                        <li class="header__header-upper__nav__nav-item font-link">
                            <a href="{% url 'blog:user_blog_list' %}">Моя лента</a>
                        </li>
                        <li class="header__header-upper__nav__nav-item font-link">
                            <a href="{% url 'profiles:profile' %}">Личный кабинет</a>
                        </li>
                    {% else %}
                        <li class="header__header-upper__nav__nav-item font-link">
                            <a href="{% url 'about' %}">О проекте</a>
                        </li>
                        <li class="header__header-upper__nav__nav-item font-link">
                            <a href="{% url 'total' %}">Блог</a>
                        </li>
                        <li class="header__header-upper__nav__nav-item font-link">
                            <a href="#">Наши менторы</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <div class="header-upper-wrapper">
                <ul class="header__header-upper__navbar__lang">
                    <li
                            class="header__header-upper__navbar__lang__lang-option font-subtitle"
                    >
                        RU
                    </li>
                </ul>
                {% if user.is_authenticated %}
                    <div
                            id="btn-login"
                            class="header__header-upper__navbar__btn btn btn-white"
                    >
                        <a href="{% url 'profiles:logout' %}">Выйти</a>
                    </div>
                {% else %}
                    <div
                            id="btn-login"
                            class="header__header-upper__navbar__btn btn btn-white"
                    >
                        <a href="{% url 'profiles:login' %}">Войти</a>
                    </div>
                    <div
                            id="btn-join"
                            class="header__header-upper__navbar__btn btn btn-primary"
                    >
                        <a href="{% url 'profiles:register' %}">Регистрация</a>
                    </div>
                {% endif %}
                <a
                        href="#"
                        class="header__header-upper__nav-burger"
                        id="header-menu-btn"
                >
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </div>
        </div>
    </div>
    <div class="header-upper__alt-nav" id="header-alt-nav">
        <ul class="container header__header-upper__nav">
            <li class="header__header-upper__nav__nav-item font-link">
                <a href="{% url 'about' %}">О проекте</a>
            </li>
            <li class="header__header-upper__nav__nav-item font-link">
                <a href="{% url 'total' %}">Блог</a>
            </li>
            <li class="header__header-upper__nav__nav-item font-link">
                <a href="#">Наши менторы</a>
            </li>
            {% if user.is_authenticated %}
                <li class="header__header-upper__nav__nav-item font-link">
                    <a href="{% url 'blog:user_blog_list' %}">Моя лента</a>
                </li>
                <li class="header__header-upper__nav__nav-item font-link">
                    <a href="{% url 'profiles:profile' %}">Личный кабинет</a>
                </li>
                <li class="header__header-upper__nav__nav-item font-link">
                    <a href="{% url 'profiles:logout' %}">Выйти</a>
                </li>
            {% else %}
                <li class="header__header-upper__nav__nav-item font-link">
                    <a href="{% url 'profiles:login' %}">Войти</a>
                </li>
                <li class="header__header-upper__nav__nav-item font-link">
                    <a href="{% url 'profiles:register' %}">Регистрация</a>
                </li>
            {% endif %}
        </ul>
    </div>
</header>
{% block content %}{% endblock content %}
<footer>
    <section class="footer">
        <div class="container">
            <ul class="footer-nav">
                <li class="footer-nav-item col-lg-3 col-md-6 col-sm-12">
                    <a href="{% url 'faq' %}" class="font-link"
                    >Часто задаваемые вопросы</a
                    >
                </li>
                <li class="footer-nav-item col-lg-3 col-md-6 col-sm-12">
                    <a href="{% url 'agreement' %}" class="font-link">
                        Пользовательское соглашение</a
                    >
                </li>
                <li
                        class="footer-nav-item col-lg-3 col-md-6 col-sm-12 footer-nav__contacts"
                >
                    <p class="font-link">Связаться с нами</p>
                    <p class="font-text-sm">+996 555 678747</p>
                    <p class="font-text-sm">mentor.kg@gmail.com</p>
                    <div class="footer-nav__contacts__icons">
                        <a
                                class="footer-nav__contacts__icons__icon"
                                id="icon-whatsapp"
                        ></a>
                        <a class="footer-nav__contacts__icons__icon" id="icon-fb"></a>
                        <a
                                class="footer-nav__contacts__icons__icon"
                                id="icon-instagram"
                        ></a>
                        <a
                                class="footer-nav__contacts__icons__icon"
                                id="icon-telegram"
                        ></a>
                    </div>
                </li>
                <li class="footer-nav-item col-lg-3 col-md-6 col-sm-12">
                    <h2 class="font-subtitle"><a href="{% url 'home' %}">Mentor.kg</a></h2>
                </li>
            </ul>
        </div>
    </section>
</footer>
<script
        src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"
></script>
<script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"
></script>
<script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"
></script>
<script
        type="text/javascript"
        src="http://code.jquery.com/jquery-1.7.js"
></script>
<script
        type="text/javascript"
        src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"
></script>
<script src="/static/scripts/header.js"></script>
<script
        type="text/javascript"
        src="/static/scripts/slick/slick.min.js"
></script>

<script src="/static/scripts/totopbtn.js"></script>
<script src="/static/scripts/mainpage.js"></script>
{% block js %}{% endblock js %}
</body>
</html>

templates/faq.html
{% extends "base.html" %}
{%  block title %}Часто задаваемые вопросы{% endblock title %}
{% block content %}
<main>
  <section>
    <div class="container">
      <div class="col-lg-9 col-md-12 col-sm-12">
        <h2 class="font-title">
          Часто задаваемые вопросы
        </h2>
        <div class="faq">
          <div class="faq__question-block">
            <h4 class="font-title-sm faq__question-block__question">
              Для чего нужен ментор?
            </h4>
            <p class="font-text faq__question-block__answer">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque
              modi itaque voluptatibus odio animi veritatis mollitia velit?
              Repellat dolor quo repudiandae nesciunt id similique, obcaecati,
              ullam iusto velit illo odit?Lorem ipsum dolor sit amet consectetur
              adipisicing elit. Quibusdam rerum laudantium dolorum voluptatem
              magnam vel delectus enim ratione quaerat, sint quam illum,
              incidunt eum. Laudantium quia rerum, quod non facilis doloribus
              porro eveniet neque iure, cum nemo. Eligendi alias quam ab
              recusandae suscipit fuga velit repudiandae, sunt, architecto
              explicabo distinctio!
            </p>
          </div>
          <div class="faq__question-block">
            <h4 class="font-title-sm faq__question-block__question">
              Для чего нужен ментор?
            </h4>
            <p class="font-text faq__question-block__answer">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque
              modi itaque voluptatibus odio animi veritatis mollitia velit?
              Repellat dolor quo repudiandae nesciunt id similique, obcaecati,
              ullam iusto velit illo odit?Lorem ipsum dolor sit amet consectetur
              adipisicing elit. Quibusdam rerum laudantium dolorum voluptatem
              magnam vel delectus enim ratione quaerat, sint quam illum,
              incidunt eum. Laudantium quia rerum, quod non facilis doloribus
              porro eveniet neque iure, cum nemo. Eligendi alias quam ab
              recusandae suscipit fuga velit repudiandae, sunt, architecto
              explicabo distinctio!
            </p>
          </div>
          <div class="faq__question-block">
            <h4 class="font-title-sm faq__question-block__question">
              Для чего нужен ментор?
            </h4>
            <p class="font-text faq__question-block__answer">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque
              modi itaque voluptatibus odio animi veritatis mollitia velit?
              Repellat dolor quo repudiandae nesciunt id similique, obcaecati,
              ullam iusto velit illo odit?Lorem ipsum dolor sit amet consectetur
              adipisicing elit. Quibusdam rerum laudantium dolorum voluptatem
              magnam vel delectus enim ratione quaerat, sint quam illum,
              incidunt eum. Laudantium quia rerum, quod non facilis doloribus
              porro eveniet neque iure, cum nemo. Eligendi alias quam ab
              recusandae suscipit fuga velit repudiandae, sunt, architecto
              explicabo distinctio!
            </p>
          </div>
          <div class="faq__question-block">
            <h4 class="font-title-sm faq__question-block__question">
              Для чего нужен ментор?
            </h4>
            <p class="font-text faq__question-block__answer">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque
              modi itaque voluptatibus odio animi veritatis mollitia velit?
              Repellat dolor quo repudiandae nesciunt id similique, obcaecati,
              ullam iusto velit illo odit?Lorem ipsum dolor sit amet consectetur
              adipisicing elit. Quibusdam rerum laudantium dolorum voluptatem
              magnam vel delectus enim ratione quaerat, sint quam illum,
              incidunt eum. Laudantium quia rerum, quod non facilis doloribus
              porro eveniet neque iure, cum nemo. Eligendi alias quam ab
              recusandae suscipit fuga velit repudiandae, sunt, architecto
              explicabo distinctio!
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock content%}

templates/forbidden.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Forbidden {% endblock%}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12 pt-5 pb-3">
        <h1 class="text-center">Mentor.kg</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-sm-10 col-md-6 col-lg-4 d-block mx-auto text-center text-light">
        <div class="py-5 px-5 bg-danger border border-light rounded">
          <p>
            <b>
              You do not have permission to perform this operation!
              Please, check whether you have permissions!
            </b>
          </p>
          <a class="text-light" href="{% url 'home' %}">Back to Main Page</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/search.html
{% extends "base.html" %} {% block title %} Наши менторы{% endblock title %} 
{% block content %}

<!-- <div class='row'>
        <div class='col-sm-3'>
          <h1>Users</h1>
           <hr/>
          {% for user in users %}
            <a href='/{{ user.username}}/'>{{ user.username}}</a><br/>

          {% empty %}
          <p>No users found</p>
          {% endfor %}
        </div>
    </div> -->

<main>
  <div class="background-blobs">
    <svg class="bg-svg" id="blobShape1" viewBox="0 0 500 500">
      <clipPath></clipPath>
      <path
        fill="url(#g1)"
        d="M 451.5,185.8 C 441.5,266.2 339.6,305 272.3,350.2 207.7,393.6 226.7,444.7 182.6,447.9 132.8,451.4 83.97,399.9 66.37,353.1 34.6,268.4 41.16,141.8 112,85.44 186.1,26.33 313.8,54.1 396,101.4 425.2,118.2 455.6,152.4 451.5,185.8 Z"
      />
      <linearGradient id="g1" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0" stop-color="#8459b5" />
        <stop offset="1" stop-color="#94d6ba" />
      </linearGradient>
    </svg>
    <section>
      <div class="container">
        <h2 class="font-title">Менторы</h2>
        <p class="font-text">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat vel,
          mollitia dolores illo.
        </p>
        <div class="mentors-wrapper">
          <form method="GET" id="blog__search-form" action="{% url 'profiles:user_list' %}">
            <div class="searchbox col-lg-8 col-md-8 col-sm-12">
              <input
                type="text"
                class="searchbox__input font-text"
                placeholder="Поиск"
                name="q"
                value="{{ request.GET.q }}"
              />
              <input type="submit" class="searchbox__icon" value="" />
            </div>
          </form>
          <div class="mentors__mentor-cards col-12">
            {% for user in object_list %}
              <div
                class="mentors__mentor-cards__mentor-card col-lg-4 col-md-6 col-sm-12"
              >
                <a href="#">
                  <div class="mentors__mentor-cards__mentor-card__img">
                    <img src="{{ user.profile.image.url }}" alt="" />
                  </div>
                </a>
                <h4
                  class="font-title-sm mentors__mentor-cards__mentor-card__name"
                >
                  <a href="{% url 'profiles:account_detail' user.username %}">{{ user.first_name}} {{ user.last_name}}</a>
                </h4>
                <h4
                  class="font-subtitle mentors__mentor-cards__mentor-card__position"
                >
                  {{ user.position }}
                </h4>
                <div class="font-text mentors__mentor-cards__mentor-card__bio">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Aspernatur molestiae voluptates accusamus minus autem adipisci
                  ducimus voluptate maiores ad recusandae.
                </div>
                <button class="btn btn-white">
                  <a href="{% url 'profiles:account_detail' user.username %}">Подробнее</a>
                </button>
              </div>
              {% empty %}
              {% if request.GET.q %}
              <p class="mt-5 mb-5 font-text col-6 offset-3" style="text-align:center">Извините, но такого ментора мы не нашли:(</p>
              {% else %}
              <p class="mt-5 mb-5 font-text col-6 offset-3" style="text-align:center">Менторов пока нет</p>
              {% endif %}
            {% endfor %}
        </div>
      </div>
    </section>
  </div>
</main>
{% endblock content %}